# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.TextField()),
                ('doc_dept', models.TextField()),
                ('doc_year', models.TextField()),
                ('doc_name', models.TextField()),
                ('hlc_cat', models.TextField()),
                ('hlc_cmpt', models.TextField()),
                ('justification', models.TextField()),
                ('submitter', models.EmailField(max_length=254)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
