# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docmetadata',
            name='upload_date',
            field=models.BigIntegerField(),
        ),
    ]
