# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171112_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docmetadata',
            old_name='upload_date',
            new_name='upload_time',
        ),
    ]
